// Code generated by gozz:wire github.com/go-zing/gozz. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	wire "github.com/google/wire"
)

// github.com/go-zing/gozz-doc-examples/bookstore.Application
func Initialize_Application() (*Application, func(), error) {
	panic(wire.Build(_Set))
}
