// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-zing/gozz-doc-examples/bookstore/impls"
)

// Injectors from wire_zinject.go:

// github.com/go-zing/gozz-doc-examples/bookstore.Application
func Initialize_Application() (*Application, func(), error) {
	bookServiceImpl := &impls.BookServiceImpl{}
	main_impl_aop_types_BookService := &_impl_aop_types_BookService{
		_aop_types_BookService: bookServiceImpl,
	}
	apis := &Apis{
		Types_BookService: main_impl_aop_types_BookService,
	}
	httpController := ProvideHttpController()
	application := &Application{
		ApisProvider:   apis,
		HttpController: httpController,
	}
	return application, func() {
	}, nil
}
