// Code generated by gozz:wire github.com/go-zing/gozz. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package main

import (
	impls "github.com/go-zing/gozz-doc-examples/bookstore/impls"
	types "github.com/go-zing/gozz-doc-examples/bookstore/types"
	wire "github.com/google/wire"
)

var (
	_Set = wire.NewSet(
		// github.com/go-zing/gozz-doc-examples/bookstore.Apis
		wire.Bind(new(ApisProvider), new(*Apis)),
		wire.Struct(new(Apis), "*"),

		// github.com/go-zing/gozz-doc-examples/bookstore.Application
		wire.Struct(new(Application), "*"),

		// github.com/go-zing/gozz-doc-examples/bookstore.HttpController
		ProvideHttpController,

		// github.com/go-zing/gozz-doc-examples/bookstore/impls.BookServiceImpl
		wire.Bind(new(_aop_types_BookService), new(*impls.BookServiceImpl)),
		wire.Struct(new(_impl_aop_types_BookService), "*"),
		wire.Bind(new(types.BookService), new(*_impl_aop_types_BookService)),
		wire.Struct(new(impls.BookServiceImpl), "*"),
	)
)
