// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package types

var (
	_types_doc = map[interface{}]map[string]string{
		(*BookService)(nil): _doc_BookService,

		(*QueryBook)(nil):     _doc_QueryBook,
		(*QueryListBook)(nil): _doc_QueryListBook,
		(*ListBook)(nil):      _doc_ListBook,
		(*FormBook)(nil):      _doc_FormBook,
		(*Book)(nil):          _doc_Book,
	}

	_values_doc = map[string]map[interface{}]string{}
)

var _doc_BookService = map[string]string{
	"":         "书籍服务接口",
	"GetBook":  "获取指定书籍",
	"ListBook": "获取书籍列表",
	"EditBook": "编辑书籍",
	"NewBook":  "新建书籍",
	"Delete":   "删除书籍",
}

var _doc_QueryBook = map[string]string{
	"":   "书籍查询参数",
	"Id": "查询指定ID",
}

func (QueryBook) FieldDoc(f string) string { return _doc_QueryBook[f] }

var _doc_QueryListBook = map[string]string{
	"":          "书籍列表查询参数",
	"Keyword":   "查询关键字",
	"PageNo":    "查询页数",
	"PageCount": "查询分页",
}

func (QueryListBook) FieldDoc(f string) string { return _doc_QueryListBook[f] }

var _doc_ListBook = map[string]string{
	"":      "书籍列表",
	"Total": "总数",
	"List":  "列表",
}

func (ListBook) FieldDoc(f string) string { return _doc_ListBook[f] }

var _doc_FormBook = map[string]string{
	"":            "书籍新建或编辑表单",
	"Id":          "ID",
	"Title":       "标题",
	"Author":      "作者",
	"Description": "描述",
}

func (FormBook) FieldDoc(f string) string { return _doc_FormBook[f] }

var _doc_Book = map[string]string{
	"CreatedAt": "创建时间",
	"CreatedBy": "创建人",
	"UpdatedAt": "更新时间",
	"UpdatedBt": "更新人",
}

func (Book) FieldDoc(f string) string { return _doc_Book[f] }
