name: gozz-doc deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install yarn@1.22.19
          yarn
          yarn docs:build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vuepress/dist
          external_repository: go-zing/gozz
          publish_branch: gh-pages